# Generated by Django 4.1.7 on 2023-04-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="resetPassword",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
